// Ollama Agent Harness — main entry point
export { queryLoop } from './core/queryLoop';
export type { QueryLoopDeps } from './core/queryLoop';
export { OllamaClient } from './core/ollamaClient';
export { RuntimeTracer, runtimeTracer } from './core/tracing';
export { HarnessError, OllamaConnectionError, ContextOverflowError, ToolExecutionError, PermissionDeniedError, withRetry, errorToToolResult } from './core/errors';
export { ToolDispatcher, getBuiltinTools, FileReadTool, FileWriteTool, FileEditTool, ListFilesTool, BashTool, WebFetchTool, ImageAnalyzeTool, AudioTranscribeTool } from './tools';
export { PermissionEngine } from './permissions/engine';
export { assembleSystemContext, assembleToolSchemas, assembleUserContext, buildInitialMessages, estimateTokenCount } from './context/assembly';
export { applyBudgetReduction, applySnip, applyAutoCompact, compactIfNeeded, validateCompactionSummary, DEFAULT_COMPACTION_CONFIG } from './context/compaction';
export { SessionStorage } from './persistence/sessionStorage';
export { resumeSession, forkSession, getLatestSession } from './persistence/resume';
export { createContinuityCheckpoint } from './persistence/continuity';
export { rebuildSemanticMemory, searchSemanticMemory } from './persistence/semanticMemory';
export { AgentTool, appendSubagentRoutingMetric, listSubagentRoutingMetrics, runSubagent, resolveSubagentConfig } from './agents/subagent';
export type { SubagentRoutingMetric } from './agents/subagent';
export { HELPER_AGENT_PRESETS, calibrateModelRoutingPolicy, createHelperAgentConfig, getHelperAgentPreset, selectModelForTask, summarizeRoutingMetrics } from './agents/modelRouting';
export type { HelperAgentPreset, HelperTaskType, ModelRoutingCalibration, ModelRoutingDecision, ModelRoutingInput, ModelRoutingPolicy, ModelTier, RoutingMetricBucket, RoutingMetricInput, RoutingMetricsSummary, TaskRisk } from './agents/modelRouting';
export { appendLearningCandidate, extractLearningCandidate, getLearningCandidateProvenance, listLearningCandidateReviews, listLearningCandidates, listReviewedLearningCandidates, promoteLearningCandidate, reviewLearningCandidate } from './learning/sessionLearning';
export type { LearningCandidateOptions, LearningCandidateProvenance, LearningCandidateProvenanceEvent, LearningCandidateReview, LearningCandidateReviewAction, PromotedLearningCandidate, ReviewedLearningCandidate, SessionLearningCandidate } from './learning/sessionLearning';
export { appendEvalTraceExample, createEvalTraceExample, createReplayEvalExample, deleteEvalTraceExample, listEvalTraceExamples, listEvalTraceRuns, readEvalTraceDataset, runEvalTraceDataset, summarizeEvalTraceRuns, updateEvalTraceExampleTags } from './learning/evalTrace';
export type { EvalTraceExample, EvalTraceOptions, EvalTraceRun, EvalTraceRunResult, EvalTraceRunTrend, ReplayEvalActuals, ReplayEvalOptions, ReplayEvalRunOptions, ReplayEvalSourceLinks, TraceSnapshot } from './learning/evalTrace';
export { loadSkillsDir, parseSkillFile, matchSkillTrigger } from './extensibility/skillLoader';
export { HookPipeline } from './extensibility/hookPipeline';
export type { LoopConfig, LoopEvent, Tool, ToolResult, ToolCall, PermissionRule, PermissionMode, SessionEvent, SessionMeta, ContinuityCheckpoint, Hook, HookContext, HookResult } from './types';
