// Ollama Agent Harness — main entry point
export { queryLoop } from './core/queryLoop';
export type { QueryLoopDeps } from './core/queryLoop';
export { OllamaClient } from './core/ollamaClient';
export { RuntimeTracer, runtimeTracer } from './core/tracing';
export { describeOutputValidationProfileSuggestion, getOutputValidationInstructions, normalizeCustomOutputValidationProfiles, OUTPUT_VALIDATION_PROFILES, OUTPUT_VALIDATION_PROFILE_TEMPLATES, parseOutputValidationProfile, suggestOutputValidationProfile, validateOutput, withOutputValidationInstructions } from './core/outputValidation';
export type { BuiltInOutputValidationProfile, CustomOutputValidationCheck, CustomOutputValidationProfile, OutputValidationFinding, OutputValidationProfile, OutputValidationProfileInfo, OutputValidationProfileTemplate, OutputValidationResult, OutputValidationStatus } from './core/outputValidation';
export { HarnessError, OllamaConnectionError, ContextOverflowError, ToolExecutionError, PermissionDeniedError, withRetry, errorToToolResult } from './core/errors';
export { ToolDispatcher, getBuiltinTools, FileReadTool, FileWriteTool, FileEditTool, ListFilesTool, BashTool, WebFetchTool, ImageAnalyzeTool, AudioTranscribeTool, PdfReadTool, PdfMetadataTool, PdfRenderPageTool, PdfExtractTablesTool, ToolRegistry, createBuiltinToolRegistry } from './tools';
export { PermissionEngine } from './permissions/engine';
export { assembleSystemContext, assembleToolSchemas, assembleUserContext, buildInitialMessages, estimateTokenCount } from './context/assembly';
export { applyBudgetReduction, applySnip, applyAutoCompact, compactIfNeeded, validateCompactionSummary, DEFAULT_COMPACTION_CONFIG } from './context/compaction';
export { SessionStorage } from './persistence/sessionStorage';
export { resumeSession, forkSession, getLatestSession } from './persistence/resume';
export { createContinuityCheckpoint } from './persistence/continuity';
export { rebuildSemanticMemory, searchSemanticMemory } from './persistence/semanticMemory';
export { getSessionSearchIndexStatus, rebuildSessionSearchIndex, rebuildSessionSearchIndexWithMetadata, searchSessions } from './persistence/sessionSearchIndex';
export type { SessionSearchEntry, SessionSearchIndexFile, SessionSearchIndexMetadata, SessionSearchIndexStatus, SessionSearchResult } from './persistence/sessionSearchIndex';
export { createAutomationJob, deleteAutomationJob, executeDueJobs, listAutomationJobs, listDueAutomationJobs, markAutomationJobRun, parseAutomationSchedule, readAutomationRunLog, updateAutomationJob } from './automation/jobs';
export type { AutomationJob, AutomationRunUpdate, AutomationSchedule, AutomationScheduleKind } from './automation/jobs';
export { buildAutomationPrompt, prepareAutomationRun } from './automation/runner';
export { AutomationScheduler } from './automation/scheduler';
export { MyceliumGraph, loadMyceliumGraph, saveMyceliumGraph } from './mycelium/graph';
export { MycelialContextRouter, createMycelialRouter } from './mycelium/router';
export { spreadActivation, selectRoute } from './mycelium/activation';
export { reinforceRoute, weakenRoute, decayUnusedEdges, computeReward } from './mycelium/reinforcement';
export { BUILTIN_MODEL_CATALOG, getModelCatalog, getModelCatalogCacheStatus, listCatalogModels, readModelCatalogCache, validateModelCatalogManifest, writeModelCatalogCache } from './models/modelCatalog';
export type { GetModelCatalogOptions, ModelCatalogCacheStatus, ModelCatalogManifest, ModelCatalogModel, ModelCatalogProvider } from './models/modelCatalog';
export { discoverExtensionManifests } from './extensibility/extensionManifest';
export type { ExtensionManifest, ExtensionManifestKind } from './extensibility/extensionManifest';
export { AgentTool, appendSubagentRoutingMetric, listSubagentRoutingMetrics, runSubagent, resolveSubagentConfig } from './agents/subagent';
export type { SubagentRoutingMetric } from './agents/subagent';
export { HELPER_AGENT_PRESETS, calibrateModelRoutingPolicy, createHelperAgentConfig, getHelperAgentPreset, selectModelForTask, summarizeRoutingMetrics } from './agents/modelRouting';
export type { HelperAgentPreset, HelperTaskType, ModelRoutingCalibration, ModelRoutingDecision, ModelRoutingInput, ModelRoutingPolicy, ModelTier, RoutingMetricBucket, RoutingMetricInput, RoutingMetricsSummary, TaskRisk } from './agents/modelRouting';
export { appendLearningCandidate, extractLearningCandidate, getLearningCandidateProvenance, listLearningCandidateReviews, listLearningCandidates, listReviewedLearningCandidates, promoteLearningCandidate, reviewLearningCandidate } from './learning/sessionLearning';
export type { LearningCandidateOptions, LearningCandidateProvenance, LearningCandidateProvenanceEvent, LearningCandidateReview, LearningCandidateReviewAction, PromotedLearningCandidate, ReviewedLearningCandidate, SessionLearningCandidate } from './learning/sessionLearning';
export { appendEvalTraceExample, createEvalTraceExample, createOutputValidationTrendExport, createReplayEvalExample, deleteEvalTraceExample, listEvalTraceExamples, listEvalTraceRuns, readEvalTraceDataset, runEvalTraceDataset, summarizeEvalTraceRuns, summarizeOutputValidationRuns, updateEvalTraceExampleTags } from './learning/evalTrace';
export type { EvalTraceExample, EvalTraceOptions, EvalTraceRun, EvalTraceRunResult, EvalTraceRunTrend, OutputValidationEvalRunOptions, OutputValidationRunTrend, OutputValidationSelectionSource, OutputValidationTrendExport, ReplayEvalActuals, ReplayEvalOptions, ReplayEvalRunOptions, ReplayEvalSourceLinks, TraceSnapshot } from './learning/evalTrace';
export { loadSkillsDir, parseSkillFile, matchSkillTrigger } from './extensibility/skillLoader';
export { HookPipeline } from './extensibility/hookPipeline';
export type { LoopConfig, LoopEvent, OutputValidationEvent, Tool, ToolResult, ToolCall, PermissionRule, PermissionMode, SessionEvent, SessionMeta, ContinuityCheckpoint, Hook, HookContext, HookResult } from './types';
